### ISSUE TITLE
Feature Request: Support conditional hooks

### ISSUE THREAD

**Issue by jpray** [luwes/swiss#14]
React forbids conditional hooks, but there are some relevant use cases.  The most common use case I encounter is "early return" where I want to short circuit my render function if certain conditions aren't met.  Most hook implementations use a counter to keep track of which hook is being run, but you can also use a partial stack trace to uniquely identify the hook and avoid the tricky issue of conditional hooks causing hook state to get messed up.

Is this something you'd consider?

**Comment by luwes** [comment]
interesting idea, do you have any examples where this is used?

Swiss does have one middleware called `thunk` which could potentially be useful for this. It allows you to conditionally render quite easily.
https://swiss.netlify.com/fixtures/middleware/thunk/

**Comment by jpray** [comment]
Here is an example:
https://codesandbox.io/s/rqjm2pov4

Thunk is cool.

**Comment by luwes** [comment]
hooks are not in v2 anymore, they can still be added with a pkg like 

https://github.com/WebReflection/augmentor
https://github.com/michael-klein/hookuspocus
