### ISSUE TITLE
initial attribute values not getting set to properties.

### ISSUE THREAD

**Issue by dredzone** [luwes/swiss#15]
@luwes thank you for a great swiss library. I was experimenting with a library and noticed that initial attribute values are not set to a corresponding properties. In below example I expect hello property set to a "world" value

```
element("my-element", () => html`<div></div>`, {observedAttributes: ["hello"]});
<my-element hello="world"/>
document.querySelector("my-element").hello // print undefined 
```

**Comment by luwes** [comment]
thanks for reporting @dredzone. I will look into this.

**Comment by luwes** [comment]
Resolved in https://github.com/luwes/swiss/commit/f87e43bc4823cda248555efd97c5229aa0b51b9a
