### ISSUE TITLE
useContext example

### ISSUE THREAD

**Issue by felipeegasneris** [luwes/swiss#16]
your doc is awesome, but I need a useContext example to share state between siblings components, greetings!

**Comment by luwes** [comment]
@felipeegasneris in the tests there is a small example on how to use the context related hooks. See here https://github.com/luwes/swiss/blob/master/packages/swiss/hooks/test/use-context.js

First you have to create a context `const Context = createContext(13);` which can be shared by components and one provides the value `Context.provide(69);`, the other can retrieve it with `useContext()`.

Hope this helps.

**Comment by felipeegasneris** [comment]
thanks for your response @luwes, but I need to create a "state machine" with context and useReducer, like all React example over the internet, I did a try, but the dispatch function doesn't change the state :(

https://codesandbox.io/s/amazing-franklin-7ehuj

**Comment by luwes** [comment]
thanks @felipeegasneris, this seems to be a bug.
I'm gonna look into it.

**Comment by luwes** [comment]
@felipeegasneris locally this works but there's seems to be a lit-html error in the codesandbox app now. screen video http://recordit.co/HOgleCNDij

**Comment by felipeegasneris** [comment]
thanks @luwes !!!
