### ISSUE TITLE
Swiss import

### ISSUE THREAD

**Issue by kethan** [luwes/swiss#17]
Hi,

Let's say I am creating 30+ custom elements for Semantic UI(http://semantic-ui.com). So for each custom element should I import swiss library or globally can I reuse the swiss library. My goal is to minimize the size for standalone elements.

**Comment by luwes** [comment]
@kethan I think the ideal way to do this is by using a peer dependency to Swiss.
https://nodejs.org/es/blog/npm/peer-dependencies/

This way Swiss is only bundled one time in the final app bundle.

The bundle of your custom elements will have 
`import { element } from 'swiss';` at the top but it will not be resolved until you actually will use the custom element in your app.
