### ISSUE TITLE
repeated attributes on 2 or more components

### ISSUE THREAD

**Issue by felipeegasneris** [luwes/swiss#24]
when I have 2 or more same components and I set different values on it, the first value is mandatory on all elements, one example:

https://codesandbox.io/s/serene-kare-634jm

I need to show the same components twice or more times with different values on start, please help me! thanks!

**Comment by felipeegasneris** [comment]
:ping:

**Comment by luwes** [comment]
thanks for reporting! I'll have a look

**Comment by luwes** [comment]
https://codesandbox.io/s/romantic-pasteur-z5hyn 🎉

**Comment by felipeegasneris** [comment]
coool! thanks a lot! 🎉
